-- DEV ONLY (H2 in-memory reset)
DELETE FROM game_genres;
DELETE FROM game;

INSERT INTO game (
    title,
    platform,
    developer,
    release_date,
    price,
    image_url,
    description,
    featured,
    favorite,
    created_at
)
VALUES
('Counter Strike 2', 'PC', 'Valve', '2023-09-27', 19.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coaczd.jpg',
'For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical leap in Counter-Strike’s history. Built on the Source 2 engine, Counter-Strike 2 is modernized with realistic physically-based rendering, state of the art networking, and upgraded Community Workshop tools.',
true, false, CURRENT_TIMESTAMP),
('The Witcher 3: Wild Hunt', 'PC', 'CD Projekt RED', '2015-05-15', 12.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coaarl.jpg',
'The Witcher 3: Wild Hunt is an open-world action role-playing game developed by CD Projekt Red. Set in a dark fantasy world, the game follows Geralt of Rivia, a monster hunter searching for his adopted daughter, Ciri, while navigating political conflicts and supernatural threats. Gameplay features exploration, combat, character progression, and branching narratives shaped by player choices. Widely acclaimed for its writing, world-building, and depth, it is considered one of the most influential RPGs of its generation. Story The Witcher 3: Wild Hunt concludes the story of the witcher Geralt of Rivia, the series protagonist, whose story to date has been covered in the previous installments. Geralts new mission comes in dark times as the mysterious and otherworldly army known as the Wild Hunt invades the Northern Kingdoms, leaving only blood soaked earth and fiery ruin in its wake; and it seems the Witcher is the key to stopping their cataclysmic rampage.',
true, false, CURRENT_TIMESTAMP),
('Cyberpunk 2077', 'Xbox', 'CD Projekt RED', '2020-12-10', 49.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coaih8.jpg',
'Cyberpunk 2077 is an open-world action-adventure game set in Night City, a sprawling metropolis driven by power, glamour, and body modification. Players assume the role of V, a mercenary outlaw in pursuit of a unique implant that holds the key to immortality. The game allows extensive customization of cyberware, skills, and playstyle. Choices made throughout the journey influence both the narrative and the world. Story In 2077, following an economic collapse sometime during the early 21st century, the United States is forced to rely on large corporations to survive. These corporations deal in a wide range of areas, such as weapons, robotics, cybernetics, pharmaceuticals, communications and biotechnology, and many of these companies operate above the law. The world in between is where decadence, sex and pop culture mix with violent crime, extreme poverty and the unattainable promise of the American Dream. You play as V, a mercenary outlaw deeply embedded in the crime-ridden city of Night City, going after a one-of-a-kind implant that is the key to immortality.',
true, false, CURRENT_TIMESTAMP),
('Elden Ring', 'PC', 'FromSoftware', '2022-02-25', 39.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg',
'Elden Ring is an action RPG developed by FromSoftware and published by Bandai Namco Entertainment, released in February 2022. Directed by Hidetaka Miyazaki, with world-building contributions from novelist George R. R. Martin, the game features an expansive open world called the Lands Between. Players assume the role of a customisable character known as the Tarnished, who must explore this world, battle formidable enemies, and seek to restore the Elden Ring to become the Elden Lord. The game builds on the challenging gameplay mechanics familiar from the Dark Souls series but introduces a more open-ended structure with vast exploration, dynamic weather, and a day-night cycle. It offers deep lore, complex characters, and an interconnected world filled with secrets, dungeons, and powerful bosses. Story: Elden Ring takes place in the Lands Between, a fictional realm over which several demigods rule. It was previously ruled over by the immortal Queen Marika, who acted as keeper of the Elden Ring, a powerful force that manifested itself as the physical concept of order. When Marika shattered the Elden Ring and disappeared, her demigod children began fighting over pieces of the Ring in an event called The Shattering. Each demigod has a shard of the Ring called a Great Rune, which corrupts them with power. In the game, the player character is a Tarnished, one of a group of exiles from the Lands Between who are summoned back after the Shattering. The player must traverse the realm to repair the Elden Ring and become the Elden Lord.',
true, false, CURRENT_TIMESTAMP),
('Fortnite', 'PC', 'Epic Games', '2020-06-29', 9.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cobssb.jpg',
'Fortnite is a free-to-play online game where you and your friends fight to be the last one standing in Battle Royale, join forces to make your own Creative games, or catch a live show at Party Royale.',
true, false, CURRENT_TIMESTAMP),
('Call of Duty: Modern Warfare', 'Playstation', 'Infinity Ward', '2019-10-25', 12.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coaarl.jpg',
'Prepare to go dark, Modern Warfare is back! The stakes have never been higher as players take on the role of lethal Tier One operators in a heart-racing saga that will affect the global balance of power. Call of Duty: Modern Warfare engulfs fans in an incredibly raw, gritty, provocative narrative that brings unrivaled intensity and shines a light on the changing nature of modern war. Players will be thrust into an immersive narrative spanning the entire game. Experience the ultimate online playground with classic multiplayer or squad-up and play cooperatively in a collection of elite operations, accessible to all skill levels.',
true, false, CURRENT_TIMESTAMP),
('FIFA 21', 'Xbox', 'EA Vancouver', '2020-10-09', 24.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co3wm2.jpg',
'Football is back with EA Sports FIFA 21, featuring more ways to team up on the street or in the stadium to enjoy even bigger victories with friends. Play the worlds game with 17,000+ players, over 700 teams in 90+ stadiums, and more than 30 leagues from all over the globe.',
true, false, CURRENT_TIMESTAMP),
('NHL 25', 'Xbox', 'EA Vancouver', '2024-10-04', 39.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co8pwh.jpg',
'From the modernized skating of Next-Gen Vision Control and an overhaul of Chel’s AI player movement to authentic Reactive Action animations — experience true hockey intelligence.',
true, false, CURRENT_TIMESTAMP),
('Enshrouded', 'PC', 'Keen Games', '2024-01-24', 23.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cob9vp.jpg',
'You are Flameborn, last ember of hope of a dying race. Awaken, survive the terror of a corrupting fog, and reclaim the lost beauty of your kingdom. Venture into a vast world, vanquish punishing bosses, build grand halls and forge your path in this co-op survival Action RPG for up to 16 players.',
false, false, CURRENT_TIMESTAMP),
('Valheim', 'PC', 'Iron Gate Studios', '2021-02-02', 19.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cob24q.jpg',
'Valheim is a brutal exploration and survival game for 1-10 players set in a procedurally-generated world inspired by Norse mythology. Craft powerful weapons, construct longhouses, and slay mighty foes to prove yourself to Odin! Story: Explore a world shrouded in mystery. Discover distinct environments with unique enemies to battle, resources to gather and secrets to uncover! Be a viking, sail the open seas in search of lands unknown, and fight bloodthirsty monsters. Raise viking longhouses and build bases that offer reprieve from the dangers ahead. Customise buildings, both inside and out, with a detailed building system. Progress through building tiers to upgrade, expand and defend your base. Struggle to survive as you gather materials and craft weapons, armor, tools, ships, and defenses. Decorate your hearths and sharpen your blades, grow crops and vegetables, prepare food, brew meads and potions, and progress as you defeat more difficult bosses and discover new recipes and blueprints.',
false, false, CURRENT_TIMESTAMP),
('Pummel Party', 'PC', 'Rebuilt Games', '2018-09-20', 22.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co20uq.jpg',
'Pummel Party is a 4-player online and local-multiplayer party game. Pummel friends or AI using a wide array of absurd items in the board mode and compete to destroy friendships in the unique collection of minigames.',
false, false, CURRENT_TIMESTAMP),
('Hogwarts Legacy', 'PC', 'Avalanche Software', '2023-02-10', 59.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coaav6.jpg',
'Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Now you can take control of the action and be at the center of your own adventure in the wizarding world. Embark on a journey through familiar and new locations as you explore and discover fantastic beasts, customize your character and craft potions, master spell casting, upgrade talents, and become the wizard you want to be. Discover the feeling of living at Hogwarts as you make allies, battle Dark wizards, and ultimately decide the fate of the wizarding world. Your legacy is what you make of it. Story: Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart. You have received a late acceptance to the Hogwarts School of Witchcraft and Wizardry and soon discover that you are no ordinary student: you possess an unusual ability to perceive and master Ancient Magic. Only you can decide if you will protect this secret for the good of all, or yield to the temptation of more sinister magic.',
false, false, CURRENT_TIMESTAMP),
('ARC Raiders', 'PC', 'Embark Studios', '2025-10-30', 45.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co9rk1.jpg',
'ARC Raiders is a multiplayer extraction adventure, set in a lethal future earth, ravaged by a mysterious mechanized threat known as ARC. Enlist as a Raider and scavenge the surface to thrive in a desolate world. But beware of the machines. Beware of Raiders preying on others. ARC Raiders blends the tension from extraction shooters with atmospheric settings from the adventure genre. Lurking threats—from deadly machines to other Raiders—create a constant ebb and flow of intensity, where every moment is charged with the thrill of high stakes. Extract valuable loot and explore the unfolding mysteries of a vibrant, lethal world. ARC Raiders supports seamless social play across PlayStation, Xbox, and PC. Play with your squad and thrive as a team, or rise in the ranks as a lone ranger. Story: Lethal machines known as ARC rule the surface, ranging from unrelenting drone swarms to mechanical giants that obliterate everything in their path. Their origins remain a mystery, but their ever-present danger is felt with every step you take. Raiders survive by kitbashing scavenged materials; using long-lost tech and looted ARC parts to craft weapons, gadgets, and gear. In Speranza, everyone has an agenda, and the Traders are no different. They’ll send you topside on missions in exchange for rewards, slowly revealing more about who they are and what they want for Speranza’s future.',
true, false, CURRENT_TIMESTAMP),
('Schedule I', 'PC', 'TVGS', '2025-03-24', 19.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co9adi.jpg',
'From small-time dope pusher to kingpin - manufacture and distribute a range of drugs throughout the grungy city of Hyland Point. Expand your empire with properties, businesses, employees and more.',
false, false, CURRENT_TIMESTAMP),
('RuneScape: Dragonwilds', 'PC', 'Jagex', '2025-04-15', 16.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co9lsl.jpg',
'On RuneScape’s forgotten continent of Ashenfall, dragons have awoken. Gather, build, skill and craft to survive in this co-operative (1-4) survival crafting game. Only by mastering survival and uncovering ancient secrets can they hope to slay the Dragon Queen—alone or with allies.',
false, false, CURRENT_TIMESTAMP),
('Phasmophobia', 'PC', 'Kinetic Games', '2020-09-18', 24.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/coamcz.jpg',
'Phasmophobia is a 4 player online co-op psychological horror where you and your team members of paranormal investigators will enter haunted locations filled with paranormal activity and gather as much evidence of the paranormal as you can. You will use your ghost hunting equipment to search for and record evidence of whatever ghost is haunting the location to sell onto a ghost removal team. You can choose to support your team by monitoring the location with CCTV cameras and motion sensors from the safety of the truck or head inside and get your hands dirty with the ghostly activity that will get increasingly hostile as time goes on.',
false, false, CURRENT_TIMESTAMP),
('Grand Theft Auto V', 'PC', 'Rockstar North', '2013-09-17', 48.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.jpg',
'Grand Theft Auto V is a vast open world game set in Los Santos, a sprawling sun-soaked metropolis struggling to stay afloat in an era of economic uncertainty and cheap reality TV. The game blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of the game’s three lead characters, playing all sides of the game’s interwoven story. Story: Los Santos: a sprawling sun-soaked metropolis full of self-help gurus, starlets and fading celebrities, once the envy of the Western world, now struggling to stay afloat in an era of economic uncertainty and cheap reality TV. Amidst the turmoil, three very different criminals plot their own chances of survival and success: Franklin, a street hustler looking for real opportunities and serious money; Michael, a professional ex-con whose retirement is a lot less rosy than he hoped it would be; and Trevor, a violent maniac driven by the chance of a cheap high and the next big score. Running out of options, the crew risks everything in a series of daring ',
false, false, CURRENT_TIMESTAMP),
('Red Dead Redemption 2', 'PC', 'Rockstar Games', '2018-10-26', 23.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg',
'Red Dead Redemption 2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Story: America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.',
false, false, CURRENT_TIMESTAMP),
('God of War', 'Playstation', 'SIE Santa Monica Studio', '2018-04-20', 43.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cobkt6.jpg',
'God of War is the sequel to God of War III as well as a continuation of the canon God of War chronology. Unlike previous installments, this game focuses on Norse mythology and follows an older and more seasoned Kratos and his son Atreus in the years since the third game. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same. Story: Many years have passed since Kratos, Spartan warrior and former Greek God of War, took his vengeance against the Greek Gods, and he now lives with his young son Atreus in ancient Norway in the realm of Midgard. The game begins after the death of the Jötunn warrior Faye, Kratos second wife and Atreus mother, whose last request was for her ashes to be spread at the highest speak of the nine realms. Kratos and Atreus prepare a funeral pyre for her, mourn her death and soon go on a hunt as per Kratos desire. However much to Kratos disappointment, Atreus proves his incompetence and lack of focus, making Kratos reconsider taking Atreus in his journey. Kratos is soon attacked by a mysterious stranger with godlike powers, and who cannot feel anything physically. After seemingly killing him, Kratos reluctantly takes Atreus with him and begins their journey.',
false, false, CURRENT_TIMESTAMP),
('Hollow Knight', 'Nintendo Switch', 'Team Cherry', '2017-02-24', 13.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cobfzp.jpg',
'A 2D metroidvania with an emphasis on close combat and exploration in which the player enters the once-prosperous now-bleak insect kingdom of Hallownest, travels through its various districts, meets friendly inhabitants, fights hostile ones and uncovers the kingdoms history while improving their combat abilities and movement arsenal by fighting bosses and accessing out-of-the-way areas. Story: Beneath the fading town of Dirtmouth sleeps a vast, ancient kingdom. Many are drawn beneath the surface, searching for riches, or glory, or answers to old secrets. As the enigmatic Knight, you’ll traverse the depths, unravel its mysteries and conquer its evils.',
false, false, CURRENT_TIMESTAMP),
('Baldurs Gate III', 'Xbox', 'Larian Studios', '2017-02-24', 34.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.jpg',
'An ancient evil has returned to Baldurs Gate, intent on devouring it from the inside out. The fate of Faerun lies in your hands. Alone, you may resist. But together, you can overcome. Story: The land of Faerûn is in turmoil. Refugees cross the wilds, fleeing the helltorn stronghold of Elturel. A vicious cult marches across the Sword Coast, uniting every race of monsters and men under the banner of a cryptic god they call the Absolute. Chaos strikes at Faerûns foundations, and none may escape its talons. Not even you. The grotesque nautiloid ship appears out of nowhere, blotting out the sun. Its writhing tentacles snatch you from where you stand. The mind flayers have come, imprisoning you on their ship, infecting you with their horrid parasite. You will become one of them. By fate or fortune, you survive when the nautiloid crashes in the Sword Coast outlands. You set out for civilisation, desperate for a cure for the parasite festering in your brain, only to take centre stage in a conspiracy that runs as deep as the Nine Hells. New enemies await. As for old foes... the shadows stir. And all roads lead to the legendary city of Baldurs Gate. ',
false, false, CURRENT_TIMESTAMP),
('Dark Souls III', 'Playstation', 'FromSoftware', '2016-03-24', 6.99,
'https://images.igdb.com/igdb/image/upload/t_cover_big/cob9ed.jpg',
'Dark Souls III is an action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment. Released in March 2016, it is the fourth entry in the Souls series and the final instalment in the Dark Souls trilogy.',
false, false, CURRENT_TIMESTAMP);


INSERT INTO game_genres (game_id, genre) VALUES
(1, 'Shooter'),
(1, 'Tactical'),
(2, 'RPG'),
(2, 'Adventure'),
(3, 'Shooter'),
(3, 'Adventure'),
(3, 'RPG'),
(4, 'RPG'),
(4, 'Adventure'),
(5, 'Shooter'),
(5, 'RPG'),
(5, 'Strategy'),
(6, 'Shooter'),
(7, 'Simulation'),
(7, 'Sport'),
(8, 'Simulation'),
(8, 'Sport'),
(9, 'RPG'),
(9, 'Adventure'),
(10, 'RPG'),
(10, 'Adventure'),
(10, 'Indie'),
(11, 'Indie'),
(11, 'Arcade'),
(11, 'Board Game'),
(12, 'RPG'),
(12, 'Adventure'),
(13, 'Shooter'),
(14, 'Simulation'),
(14, 'Indie'),
(14, 'Strategy'),
(15, 'RPG'),
(15, 'Adventure'),
(16, 'Puzzle'),
(16, 'Tactical'),
(16, 'Indie'),
(17, 'Shooter'),
(17, 'Racing'),
(17, 'Adventure'),
(18, 'Shooter'),
(18, 'RPG'),
(18, 'Adventure'),
(19, 'RPG'),
(19, 'Adventure'),
(20, 'Adventure'),
(20, 'Indie'),
(21, 'RPG'),
(21, 'Strategy'),
(21, 'RPG'),
(21, 'Adventure'); --Dark Souls III